Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]

  resources :events, only: [:new, :create, :show, :edit, :update]

  resources :bookings, only: [:new, :create, :update]

  root 'static_pages#home'
  get 'users/:id/event'   => 'users#event'
  get 'users/:id/ticket'  => 'users#ticket'
  get 'mypage'    => 'mypages#mypage'
  get 'events/:id/replication'  => 'events#replication'
  get 'search', to: 'events#search'

  get  '/about'      => 'static_pages#about'
  get  '/guide'      => 'static_pages#guide'
  get  '/terms'      => 'static_pages#terms'
  get  '/faq'        => 'static_pages#faq'
  get  '/privacy'    => 'static_pages#privacy'
  get  '/company'    => 'static_pages#company'
  get  '/contact'    => 'static_pages#contact'
  get  '/advertise'  => 'static_pages#advertise'

  # 都道府県別イベント一覧
  get  '/hokkaido'   => 'prefectures#hokkaido'
  get  '/aomori'     => 'prefectures#aomori'
  get  '/akita'      => 'prefectures#akita'
  get  '/iwate'      => 'prefectures#iwate'
  get  '/miyagi'     => 'prefectures#miyagi'
  get  '/yamagata'   => 'prefectures#yamagata'
  get  '/fukushima'  => 'prefectures#fukushima'
  get  '/ibaraki'    => 'prefectures#ibaraki'
  get  '/tochigi'    => 'prefectures#tochigi'
  get  '/gunma'      => 'prefectures#gunma'
  get  '/saitama'    => 'prefectures#saitama'
  get  '/chiba'      => 'prefectures#chiba'
  get  '/tokyo'      => 'prefectures#tokyo'
  get  '/kanagawa'   => 'prefectures#kanagawa'
  get  '/niigata'    => 'prefectures#niigata'
  get  '/toyama'     => 'prefectures#toyama'
  get  '/ishikawa'   => 'prefectures#ishikawa'
  get  '/fukui'      => 'prefectures#fukui'
  get  '/yamanashi'  => 'prefectures#yamanashi'
  get  '/nagano'     => 'prefectures#nagano'
  get  '/gifu'       => 'prefectures#gifu'
  get  '/shizuoka'   => 'prefectures#shizuoka'
  get  '/aichi'      => 'prefectures#aichi'
  get  '/mie'        => 'prefectures#mie'
  get  '/shiga'      => 'prefectures#shiga'
  get  '/kyoto'      => 'prefectures#kyoto'
  get  '/osaka'      => 'prefectures#osaka'
  get  '/hyogo'      => 'prefectures#hyogo'
  get  '/nara'       => 'prefectures#nara'
  get  '/wakayama'   => 'prefectures#wakayama'
  get  '/tottori'    => 'prefectures#tottori'
  get  '/shimane'    => 'prefectures#shimane'
  get  '/okayama'    => 'prefectures#okayama'
  get  '/hiroshima'  => 'prefectures#hiroshima'
  get  '/yamaguchi'  => 'prefectures#yamaguchi'
  get  '/tokushima'  => 'prefectures#tokushima'
  get  '/kagawa'     => 'prefectures#kagawa'
  get  '/ehime'      => 'prefectures#ehime'
  get  '/kochi'      => 'prefectures#kochi'
  get  '/fukuoka'    => 'prefectures#fukuoka'
  get  '/saga'       => 'prefectures#saga'
  get  '/nagasaki'   => 'prefectures#nagasaki'
  get  '/kumamoto'   => 'prefectures#kumamoto'
  get  '/oita'       => 'prefectures#oita'
  get  '/miyazaki'   => 'prefectures#miyazaki'
  get  '/kagoshima'  => 'prefectures#kagoshima'
  get  '/okinawa'    => 'prefectures#okinawa'

  # スポーツ種目別イベント一覧
  get  '/other_sports'        => 'sports_types#other_sports'
  get  '/running'             => 'sports_types#running'
  get  '/walking'             => 'sports_types#walking'
  get  '/yoga'                => 'sports_types#yoga'
  get  '/pilates'             => 'sports_types#pilates'
  get  '/training'            => 'sports_types#training'
  get  '/bouldering'          => 'sports_types#bouldering'
  get  '/golf'                => 'sports_types#golf'
  get  '/football'            => 'sports_types#football'
  get  '/swimming'            => 'sports_types#swimming'
  get  '/marine_sports'       => 'sports_types#marine_sports'
  get  '/boxing'              => 'sports_types#boxing'
  get  '/kickboxing'          => 'sports_types#kickboxing'
  get  '/fighting_sports'     => 'sports_types#fighting_sports'
  get  '/ballet'              => 'sports_types#ballet'
  get  '/gym'                 => 'sports_types#gym'
  get  '/dance'               => 'sports_types#dance'
  get  '/baseball'            => 'sports_types#baseball'
  get  '/tennis'              => 'sports_types#tennis'
  get  '/table_tennis'        => 'sports_types#table_tennis'
  get  '/badminton'           => 'sports_types#badminton'
  get  '/basketball'          => 'sports_types#basketball'
  get  '/volleyball'          => 'sports_types#volleyball'
  get  '/skiing'              => 'sports_types#skiing'
  get  '/skate'               => 'sports_types#skate'
  get  '/winter_sports'       => 'sports_types#winter_sports'
  get  '/bowling'             => 'sports_types#bowling'
  get  '/darts'               => 'sports_types#darts'
  get  '/billiards'           => 'sports_types#billiards'
  get  '/bodycare'            => 'sports_types#bodycare'
  get  '/treatment'           => 'sports_types#treatment'
  get  '/relaxation'          => 'sports_types#relaxation'
  get  '/other_treatments'    => 'sports_types#other_treatments'
  get  '/squash'              => 'sports_types#squash'
  get  '/triathlon'           => 'sports_types#triathlon'
  get  '/bicycle'             => 'sports_types#bicycle'
  get  '/batontwirling'       => 'sports_types#batontwirling'

  # 開催日別イベント一覧
  get  '/today'      => 'eventdates#today'
  get  '/tomorrow'   => 'eventdates#tomorrow'
  get  '/thisweek'   => 'eventdates#thisweek'
  get  '/nextweek'   => 'eventdates#nextweek'
  get  '/thismonth'  => 'eventdates#thismonth'
  get  '/nextmonth'  => 'eventdates#nextmonth'
  get  '/monday'     => 'eventdates#monday'
  get  '/tuesday'    => 'eventdates#tuesday'
  get  '/wednesday'  => 'eventdates#wednesday'
  get  '/thursday'   => 'eventdates#thursday'
  get  '/friday'     => 'eventdates#friday'
  get  '/saturday'   => 'eventdates#saturday'
  get  '/sunday'     => 'eventdates#sunday'

  # イベント特徴一覧
  get '/free_trial'      => 'features#free_trial'
  get '/trial_event'     => 'features#trial_event'
  get '/beginner'        => 'features#beginner'
  get '/body_make'       => 'features#body_make'
  get '/diet'            => 'features#diet'
  get '/anti_aging'      => 'features#anti_aging'
  get '/moning_activity' => 'features#moning_activity'
  get '/women_only'      => 'features#women_only'
  get '/nursery'         => 'features#nursery'
  get '/children'        => 'features#children'
  get '/parent_child'    => 'features#parent_child'
  get '/matching'        => 'features#matching'
  get '/friends'         => 'features#friends'
  get '/seminar'         => 'features#seminar'
  get '/nutrition'       => 'features#nutrition'
  get '/mental'          => 'features#mental'
  get '/relax'           => 'features#relax'

end
