# Set the host name for URL creation
SitemapGenerator::Sitemap.default_host = "https://event.bodymate.jp/"

SitemapGenerator::Sitemap.create do
  add root_path
  add about_path

  # 各検索カテゴリー
  add hokkaido_path
  add aomori_path
  add akita_path
  add iwate_path
  add miyagi_path
  add yamagata_path
  add fukushima_path
  add ibaraki_path
  add tochigi_path
  add gunma_path
  add saitama_path
  add chiba_path
  add tokyo_path
  add kanagawa_path
  add niigata_path
  add toyama_path
  add ishikawa_path
  add fukui_path
  add yamanashi_path
  add nagano_path
  add gifu_path
  add shizuoka_path
  add aichi_path
  add mie_path
  add shiga_path
  add kyoto_path
  add osaka_path
  add hyogo_path
  add nara_path
  add wakayama_path
  add tottori_path
  add shimane_path
  add okayama_path
  add hiroshima_path
  add yamaguchi_path
  add tokushima_path
  add kagawa_path
  add ehime_path
  add kochi_path
  add fukuoka_path
  add saga_path
  add nagasaki_path
  add kumamoto_path
  add oita_path
  add miyazaki_path
  add kagoshima_path
  add okinawa_path
  add other_sports_path
  add running_path
  add walking_path
  add yoga_path
  add pilates_path
  add training_path
  add bouldering_path
  add golf_path
  add football_path
  add swimming_path
  add marine_sports_path
  add boxing_path
  add kickboxing_path
  add fighting_sports_path
  add ballet_path
  add gym_path
  add dance_path
  add baseball_path
  add tennis_path
  add table_tennis_path
  add badminton_path
  add basketball_path
  add volleyball_path
  add skiing_path
  add skate_path
  add winter_sports_path
  add bowling_path
  add darts_path
  add billiards_path
  add bodycare_path
  add treatment_path
  add relaxation_path
  add other_treatments_path
  add seminar_path
  add nutrition_path
  add mental_path
  add squash_path
  add today_path
  add tomorrow_path
  add thisweek_path
  add nextweek_path
  add thismonth_path
  add nextmonth_path
  add monday_path
  add tuesday_path
  add wednesday_path
  add thursday_path
  add friday_path
  add saturday_path
  add sunday_path
  add free_trial_path
  add trial_event_path
  add beginner_path
  add body_make_path
  add diet_path
  add anti_aging_path
  add moning_activity_path
  add women_only_path
  add nursery_path
  add children_path
  add parent_child_path
  add matching_path
  add friends_path

  # 各イベントページをsitemapに追加する
  Event.find_each do |event|
    add event_path(event), :lastmod => event.updated_at
  end
end
